### ISSUE TITLE
getting started examples

### ISSUE THREAD

**Issue by xAdvitya** [CosmogicOfficial/QuantumAlert#1]
### it should have alertbox with *"Nice to meet you"*

![Screenshot (406)](https://user-images.githubusercontent.com/54709416/90152349-5abe8880-dda5-11ea-9bdc-0893f6e92a23.png)

browser : firefox (latest) 
os: windows 10

**Comment by Iam1nv3nt0r** [comment]
Thanks, For your help in making the project better 👍🏻
